// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7v5QRuJt9Ynb3AUGHT1d2enKiV0-h1k',
    appId: '1:460098042328:web:5ffcace16013ecbd379aad',
    messagingSenderId: '460098042328',
    projectId: 'employee-project-e8211',
    authDomain: 'employee-project-e8211.firebaseapp.com',
    storageBucket: 'employee-project-e8211.firebasestorage.app',
    measurementId: 'G-9GYYH4CDYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa9T1af-dt2yxJ1jWMnI_kQ5K_wJxhbtw',
    appId: '1:460098042328:android:77f5be81a6f4f63c379aad',
    messagingSenderId: '460098042328',
    projectId: 'employee-project-e8211',
    storageBucket: 'employee-project-e8211.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb7v5QRuJt9Ynb3AUGHT1d2enKiV0-h1k',
    appId: '1:460098042328:web:9d67054a15ad3219379aad',
    messagingSenderId: '460098042328',
    projectId: 'employee-project-e8211',
    authDomain: 'employee-project-e8211.firebaseapp.com',
    storageBucket: 'employee-project-e8211.firebasestorage.app',
    measurementId: 'G-7NMPLZMV3W',
  );
}
